version: '3'

services:
  app:
    build:
      context: container/nginx/
    container_name: eshop-nginx
    depends_on:
      - phpfpm
    links:
      - phpfpm
      - oxid6_mailhog:mail.server
    volumes:
      - ./data/www/:/var/www/html:cached
    ports:
      - ${APACHE_PORT}:80
      - ${APACHE_HTTPS_PORT}:443
    networks: &appnetworks
      - www

  phpfpm:
    build:
      context: container/php/
    container_name: eshop-auna
    environment:
        OXID_VERSION: dev-b-6.2-ce
        OXID_DEMODATA: 1
    volumes:
      - ./data/www/:/var/www/:cached
    networks: *appnetworks
    env_file: ./container/php/.env

  oxid6_mysql:
    image: mysql:5.7
    hostname: mysql.${DOMAIN}
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks: *appnetworks

  oxid6_mailhog:
    hostname: mailhog.${DOMAIN}
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
    networks: *appnetworks

  oxid6_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: oxid6_mysql
    networks: *appnetworks

networks:
  www:
